In [146]:
import os
import tweepy as tw
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

In [147]:
consumer_key= 'Kzzmf7XB9oZCv**********'
consumer_secret= '*******************4ndkOgBVCCft2Xx8qyL3cA'
access_token= '1263115900**************************************'
access_token_secret= '0Ht7ZyTxvL04crIhBJl32CYHPYV*****************'

In [148]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\varlock^_^\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [149]:
auth = tw.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tw.API(auth, wait_on_rate_limit=True)

In [150]:
def Search(username):
    for tweet in api.user_timeline(id=username, count=count):
        myposts.append((tweet.created_at.strftime('%y-%m-%d %a %H:%M:%S'),tweet.user.screen_name,tweet.text))


In [151]:
myposts=[]
username = 'augustin3_jose'
count = 10
Search(username)
df = pd.DataFrame(myposts,columns=['Date Posted','User Name','Tweet'])

In [152]:
df

Date Posted       User Name  \
0  20-07-14 Tue 00:42:42  augustin3_jose   
1  20-07-14 Tue 00:38:49  augustin3_jose   
2  20-07-13 Mon 23:55:26  augustin3_jose   
3  20-07-13 Mon 23:42:03  augustin3_jose   
4  20-07-13 Mon 23:40:10  augustin3_jose   
5  20-07-13 Mon 23:33:24  augustin3_jose   
6  20-07-13 Mon 23:30:41  augustin3_jose   
7  20-07-13 Mon 23:29:24  augustin3_jose   
8  20-07-13 Mon 23:21:56  augustin3_jose   
9  20-07-13 Mon 23:19:55  augustin3_jose   

                                               Tweet  
0  "It is only when they go wrong that machines r...  
1    VELD 2020 is the one I missed the most in 2020.  
2  Sapiens: an awesome book on evolution.. stone-...  
3  Sometimes https://t.co/C4qt2AQtPw helps me to ...  
4  I think the present educational institutions c...  
5  Suggest everyone to read Rich Dad Poor Dad: It...  
6  Invest money now: The right time to invest mon...  
7  White Paper: I would suggest to download and p...  
8     The Big short: a must-watch movie right now..!  
9  Quantum technology is an emerging field of phy...

In [153]:
#getting vectors from text using Tfidf
def get_vectors(text):
    #text = [t for t in str]
    tfidf_vectorizer = TfidfVectorizer(text)
    tfidf_vectorizer.fit(text)
    return tfidf_vectorizer.transform(text).toarray()
#text_1_array = tfidf_vectorizer.transform(tokens_without_sw_text_1).toarray()
#text_1_array

def get_cosine_sim(vectors):
    return cosine_similarity(vectors)

In [154]:
text = [t for t in df.Tweet]

In [155]:
vectors = get_vectors(text) # getting vector
cos_sim = get_cosine_sim(vectors) #cosine similarity
cos_sim

array([[1.        , 0.06741184, 0.        , 0.06103794, 0.        ,
        0.07184351, 0.05110424, 0.08881037, 0.        , 0.0198757 ],
       [0.06741184, 1.        , 0.04773349, 0.        , 0.0772239 ,
        0.03955016, 0.11176628, 0.        , 0.05830578, 0.06130051],
       [0.        , 0.04773349, 1.        , 0.03591799, 0.06193225,
        0.04369208, 0.04003677, 0.04129921, 0.02910858, 0.11289034],
       [0.06103794, 0.        , 0.03591799, 1.        , 0.02905431,
        0.02976028, 0.02727052, 0.05132474, 0.        , 0.12048631],
       [0.        , 0.0772239 , 0.06193225, 0.02905431, 1.        ,
        0.0513147 , 0.04702169, 0.03340722, 0.04709226, 0.02578673],
       [0.07184351, 0.03955016, 0.04369208, 0.02976028, 0.0513147 ,
        1.        , 0.03317295, 0.14280184, 0.02411826, 0.01320665],
       [0.05110424, 0.11176628, 0.04003677, 0.02727052, 0.04702169,
        0.03317295, 1.        , 0.03135618, 0.29095508, 0.03436953],
       [0.08881037, 0.        , 0.0412992

In [156]:
pca=PCA(n_components=2)

In [157]:
pca.fit(cos_sim)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [158]:
x_pca=pca.transform(cos_sim)

In [159]:
cos_sim.shape

(10, 10)

In [160]:
x_pca.shape #converted to 2 dimention

(10, 2)

In [161]:
x_pca

array([[-0.24713623, -0.39173644],
       [ 0.20826311,  0.0615023 ],
       [-0.12972199,  0.43672142],
       [-0.34370291,  0.2936762 ],
       [ 0.02501734,  0.11126726],
       [-0.29100971, -0.46829393],
       [ 0.67481576, -0.11617422],
       [-0.40683919, -0.43156864],
       [ 0.72906611, -0.0821803 ],
       [-0.21875228,  0.58678635]])

In [162]:
kmeans=KMeans(n_clusters=4)

In [163]:
kmeans.fit(x_pca)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=4, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [164]:
clusters=kmeans.cluster_centers_ #finding clusters

In [165]:
print(clusters)

[[ 0.70194093 -0.09917726]
 [ 0.11664023  0.08638478]
 [-0.31499504 -0.43053301]
 [-0.23072573  0.43906133]]
